export const FETCH_DOCUMENTS_PENDING = 'FETCH_DOCUMENTS_PENDING';
export const FETCH_DOCUMENTS_REJECTED = 'FETCH_DOCUMENTS_REJECTED';
export const FETCH_DOCUMENTS_FULFILLED = 'FETCH_DOCUMENTS_FULFILLED';

export const FETCH_USER_DOCUMENTS_PENDING = 'FETCH_USER_DOCUMENTS_PENDING';
export const FETCH_USER_DOCUMENTS_REJECTED = 'FETCH_USER_DOCUMENTS_REJECTED';
export const FETCH_USER_DOCUMENTS_FULFILLED = 'FETCH_USER_DOCUMENTS_FULFILLED';

export const CREATE_DOCUMENT_PENDING = 'CREATE_DOCUMENT_PENDING';
export const CREATE_DOCUMENT_REJECTED = 'CREATE_DOCUMENT_REJECTED';
export const CREATE_DOCUMENT_FULFILLED = 'CREATE_DOCUMENT_FULFILLED';

export const DELETE_DOCUMENT_PENDING = 'DELETE_DOCUMENT_PENDING';
export const DELETE_DOCUMENT_REJECTED = 'DELETE_DOCUMENT_REJECTED';
export const DELETE_DOCUMENT_FULFILLED = 'DELETE_DOCUMENT_FULFILLED';


export const SIGN_UP_PENDING = 'SIGN_UP_PENDING';
export const SIGN_UP_REJECTED = 'SIGN_UP_REJECTED';
export const SIGN_UP_FULFILLED = 'SIGN_UP_FULFILLED';

export const LOGIN_PENDING = 'LOGIN_PENDING';
export const LOGIN_REJECTED = 'LOGIN_REJECTED';
export const LOGIN_FULFILLED = 'LOGIN_FULFILLED';

export const LOGOUT_PENDING = 'LOGOUT_PENDING';
export const LOGOUT_REJECTED = 'LOGOUT_REJECTED';
export const LOGOUT_FULFILLED = 'LOGOUT_FULFILLED';

export const FETCH_ALL_USERS_PENDING = 'FETCH_ALL_USERS_PENDING';
export const FETCH_ALL_USERS_REJECTED = 'FETCH_ALL_USERS_REJECTED';
export const FETCH_ALL_USERS_FULFILLED = 'FETCH_ALL_USERS_FULFILLED';
