export const FETCH_ALL_DOCUMENTS_PENDING = 'FETCH_ALL_DOCUMENTS_PENDING';
export const FETCH_ALL_DOCUMENTS_REJECTED = 'FETCH_ALL_DOCUMENTS_REJECTED';
export const FETCH_ALL_DOCUMENTS_FULFILLED = 'FETCH_ALL_DOCUMENTS_FULFILLED';

export const FETCH_USER_DOCUMENTS_PENDING = 'FETCH_USER_DOCUMENTS_PENDING';
export const FETCH_USER_DOCUMENTS_REJECTED = 'FETCH_USER_DOCUMENTS_REJECTED';
export const FETCH_USER_DOCUMENTS_FULFILLED = 'FETCH_USER_DOCUMENTS_FULFILLED';

export const CREATE_DOCUMENT_PENDING = 'CREATE_DOCUMENT_PENDING';
export const CREATE_DOCUMENT_REJECTED = 'CREATE_DOCUMENT_REJECTED';
export const CREATE_DOCUMENT_FULFILLED = 'CREATE_DOCUMENT_FULFILLED';

export const DELETE_DOCUMENT_PENDING = 'DELETE_DOCUMENT_PENDING';
export const DELETE_DOCUMENT_REJECTED = 'DELETE_DOCUMENT_REJECTED';
export const DELETE_DOCUMENT_FULFILLED = 'DELETE_DOCUMENT_FULFILLED';

export const UPDATE_DOCUMENT_PENDING = 'UPDATE_DOCUMENT_PENDING';
export const UPDATE_DOCUMENT_REJECTED = 'UPDATE_DOCUMENT_REJECTED';
export const UPDATE_DOCUMENT_FULFILLED = 'UPDATE_DOCUMENT_FULFILLED';

export const GET_DOCUMENT_PENDING = 'GET_DOCUMENT_PENDING';
export const GET_DOCUMENT_REJECTED = 'GET_DOCUMENT_REJECTED';
export const GET_DOCUMENT_FULFILLED = 'GET_DOCUMENT_FULFILLED';


export const SIGN_UP_PENDING = 'SIGN_UP_PENDING';
export const SIGN_UP_REJECTED = 'SIGN_UP_REJECTED';
export const SIGN_UP_FULFILLED = 'SIGN_UP_FULFILLED';

export const LOGIN_PENDING = 'LOGIN_PENDING';
export const LOGIN_REJECTED = 'LOGIN_REJECTED';
export const LOGIN_FULFILLED = 'LOGIN_FULFILLED';

export const LOGOUT_PENDING = 'LOGOUT_PENDING';
export const LOGOUT_FULFILLED = 'LOGOUT_FULFILLED';

export const FETCH_ALL_USERS_PENDING = 'FETCH_ALL_USERS_PENDING';
export const FETCH_ALL_USERS_REJECTED = 'FETCH_ALL_USERS_REJECTED';
export const FETCH_ALL_USERS_FULFILLED = 'FETCH_ALL_USERS_FULFILLED';

export const UPDATE_USER_PENDING = 'UPDATE_USER_PENDING';
export const UPDATE_USER_REJECTED = 'UPDATE_USER_REJECTED';
export const UPDATE_USER_FULFILLED = 'UPDATE_USER_FULFILLED';

export const DELETE_USER_PENDING = 'DELETE_USER_PENDING';
export const DELETE_USER_REJECTED = 'DELETE_USER_REJECTED';
export const DELETE_USER_FULFILLED = 'DELETE_USER_FULFILLED';

export const GET_USER_PENDING = 'GET_USER_PENDING';
export const GET_USER_REJECTED = 'GET_USER_REJECTED';
export const GET_USER_FULFILLED = 'GET_USER_FULFILLED';


export const SEARCH_USERS_PENDING = 'SEARCH_USERS_PENDING';
export const SEARCH_USERS_REJECTED = 'SEARCH_USERS_REJECTED';
export const SEARCH_USERS_FULFILLED = 'SEARCH_USERS_FULFILLED';

export const SEARCH_DOCUMENTS_PENDING = 'SEARCH_DOCUMENTS_PENDING';
export const SEARCH_DOCUMENTS_REJECTED = 'SEARCH_DOCUMENTS_REJECTED';
export const SEARCH_DOCUMENTS_FULFILLED = 'SEARCH_DOCUMENTS_FULFILLED';


export const DEFAULT_LIMIT = 10;
export const DEFAULT_OFFSET = 0;
