export const ActionTypes = {
  FETCH_ALL_DOCUMENTS_PENDING: 'FETCH_ALL_DOCUMENTS_PENDING',
  FETCH_ALL_DOCUMENTS_REJECTED: 'FETCH_ALL_DOCUMENTS_REJECTED',
  FETCH_ALL_DOCUMENTS_FULFILLED: 'FETCH_ALL_DOCUMENTS_FULFILLED',

  FETCH_USER_DOCUMENTS_PENDING: 'FETCH_USER_DOCUMENTS_PENDING',
  FETCH_USER_DOCUMENTS_REJECTED: 'FETCH_USER_DOCUMENTS_REJECTED',
  FETCH_USER_DOCUMENTS_FULFILLED: 'FETCH_USER_DOCUMENTS_FULFILLED',

  CREATE_DOCUMENT_PENDING: 'CREATE_DOCUMENT_PENDING',
  CREATE_DOCUMENT_REJECTED: 'CREATE_DOCUMENT_REJECTED',
  CREATE_DOCUMENT_FULFILLED: 'CREATE_DOCUMENT_FULFILLED',

  DELETE_DOCUMENT_PENDING: 'DELETE_DOCUMENT_PENDING',
  DELETE_DOCUMENT_REJECTED: 'DELETE_DOCUMENT_REJECTED',
  DELETE_DOCUMENT_FULFILLED: 'DELETE_DOCUMENT_FULFILLED',

  UPDATE_DOCUMENT_PENDING: 'UPDATE_DOCUMENT_PENDING',
  UPDATE_DOCUMENT_REJECTED: 'UPDATE_DOCUMENT_REJECTED',
  UPDATE_DOCUMENT_FULFILLED: 'UPDATE_DOCUMENT_FULFILLED',

  GET_DOCUMENT_PENDING: 'GET_DOCUMENT_PENDING',
  GET_DOCUMENT_REJECTED: 'GET_DOCUMENT_REJECTED',
  GET_DOCUMENT_FULFILLED: 'GET_DOCUMENT_FULFILLED',


  SIGN_UP_PENDING: 'SIGN_UP_PENDING',
  SIGN_UP_REJECTED: 'SIGN_UP_REJECTED',
  SIGN_UP_FULFILLED: 'SIGN_UP_FULFILLED',

  LOGIN_PENDING: 'LOGIN_PENDING',
  LOGIN_REJECTED: 'LOGIN_REJECTED',
  LOGIN_FULFILLED: 'LOGIN_FULFILLED',

  LOGOUT_PENDING: 'LOGOUT_PENDING',
  LOGOUT_FULFILLED: 'LOGOUT_FULFILLED',

  FETCH_ALL_USERS_PENDING: 'FETCH_ALL_USERS_PENDING',
  FETCH_ALL_USERS_REJECTED: 'FETCH_ALL_USERS_REJECTED',
  FETCH_ALL_USERS_FULFILLED: 'FETCH_ALL_USERS_FULFILLED',

  UPDATE_USER_PENDING: 'UPDATE_USER_PENDING',
  UPDATE_USER_REJECTED: 'UPDATE_USER_REJECTED',
  UPDATE_USER_FULFILLED: 'UPDATE_USER_FULFILLED',

  DELETE_USER_PENDING: 'DELETE_USER_PENDING',
  DELETE_USER_REJECTED: 'DELETE_USER_REJECTED',
  DELETE_USER_FULFILLED: 'DELETE_USER_FULFILLED',

  GET_USER_PENDING: 'GET_USER_PENDING',
  GET_USER_REJECTED: 'GET_USER_REJECTED',
  GET_USER_FULFILLED: 'GET_USER_FULFILLED',


  SEARCH_USERS_PENDING: 'SEARCH_USERS_PENDING',
  SEARCH_USERS_REJECTED: 'SEARCH_USERS_REJECTED',
  SEARCH_USERS_FULFILLED: 'SEARCH_USERS_FULFILLED',

  SEARCH_DOCUMENTS_PENDING: 'SEARCH_DOCUMENTS_PENDING',
  SEARCH_DOCUMENTS_REJECTED: 'SEARCH_DOCUMENTS_REJECTED',
  SEARCH_DOCUMENTS_FULFILLED: 'SEARCH_DOCUMENTS_FULFILLED'
};

export const Pagination = {
  DEFAULT_LIMIT: 10,
  DEFAULT_OFFSET: 0
};
